### ISSUE TITLE
1.14.4 fix your capability

### ISSUE THREAD

**Issue by loordgek** [AshIndigo/Storage_Cabinet#4]
in TileEntityStorageCabinet make a field that holds a LazyOptional
and call from TileEntityStorageCabinet.remove https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/common/util/LazyOptional.java#L294

**Comment by AshIndigo** [comment]
Sorry for the late reply, but I've moved over to Fabric for the time being, so I won't be updating the 1.14 Forge version of this mod.
